name = "photocash-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
BOT_TOKEN = "8738784866:AAFk8eHwv2xuswJTCBxGcvKAwZuUJHq4bK0"
USER_DB_URL = "https://photo-cash-2-default-rtdb.firebaseio.com"
WEB_APP_URL = "https://ais-pre-2cfqiwuo2yblyziu3t5py4-837591927600.asia-east1.run.app"
